#=================================================
#虚拟机
#=================================================

name: 单机测试

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '00.sh'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: 查看
      uses: actions/checkout@master

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
     
#    - name: 克隆源代码
#      env: 
#        REPO_URL: https://github.com/g0g001/lede
#        REPO_BRANCH: master
#      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

#    - name: 下载软件更新
#      run: cd openwrt && ./scripts/feeds update -a

#    - name: 安装软件更新
#      run: cd openwrt && ./scripts/feeds install -a

    - name: 加载自定义配置
      run: |
        mkdir openwrt
        pwd > 00.txt
        ls >> 00.txt
        mv cs.sh openwrt/cs.sh
        mv 00.txt openwrt/00.txt
        cd openwrt
        mkdir bin
        mv cs.sh bin/cs.sh
        mv 00.txt bin/00.txt
        cd ../

    - name: SSH connection to Actions
      uses: g0g001/debugger-action@master

    - name: 上载bin目录
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: OpenWrt_bin
        path: openwrt/bin
